### ISSUE TITLE
Division and const

### ISSUE THREAD

**Issue by ReinBentdal** [ReinBentdal/division#21]
Since the `StyleClass` widget add new style using methods, there is no way of making it a `const`. That is because changes is made through the methods instead of being defined in the constructor. I dont know the exact performance difference, but it may be significant. Everything would have to be defined in the constructor like:
```dart
StyleClass(
  width: 100,
  height: 100,
  backgroundColor: ColorClass.hex('f5f5f5'),
  etc
)
```
or even
```dart
Division(
  child: Widget,
  onTap: () {},
  width: 100,
  elevation: Elevation(10),
  etc
)
```
Dart that could change help:
- https://github.com/dart-lang/language/issues/357
- extension methods

**Comment by MasiaVittorio** [comment]
Personally, I'd rather see the new constructor system on styles / gestures separately (not directly on the Division widget) because the separation between styles, gestures and children is what currently makes division cool imho!
