### ISSUE TITLE
Missing possibility to customize gesture behavior

### ISSUE THREAD

**Issue by MasiaVittorio** [ReinBentdal/division#22]
Normally, to detect a gesture on a container that does not have a background color,  one would need to set `GestureDetector(behavior: HitTestBehavior.opaque)`  

(for example, you could need a transparent background on a tappable region because it is contained inside a rounded widget and you don't want to cover the rounded border with the color of the tappable rectangular region).

It would be cool to add that property to GestureClass

**Comment by MasiaVittorio** [comment]
Same is true also for the other GestureDetector properties, like excludeFromSemantics and dragStartBehavior.

It would be cool to be able to set them via the GestureClass :D

**Comment by ReinBentdal** [comment]
Will look into that!

**Comment by ReinBentdal** [comment]
This feature was added in version 0.6.4

**Comment by MasiaVittorio** [comment]
You are a hero! Thank you!
