### ISSUE TITLE
OverflowType.hidden could apply the same borderRadius as the actual container

### ISSUE THREAD

**Issue by MasiaVittorio** [ReinBentdal/division#23]
It would be cool to clip the content of the Division following the rounded corners set in ..borderRadius() when the overflow parameter is set to "hidden".

Or maybe a whole separate parameter could enforce that behavior, like "roundClip = true" or something!

**Comment by ReinBentdal** [comment]
Noted. Will be a feature by default when overflow is set to hidden

**Comment by ReinBentdal** [comment]
Added to the development branch
