### ISSUE TITLE
background.image should expose a raw ImageProvider

### ISSUE THREAD

**Issue by MasiaVittorio** [ReinBentdal/division#26]
I use CachedNetworkImage a lot and it's not possible to pass that as the image parameter of a division.
A simple ImageProvider could allow the user to use whatever alternative provider he or she wants other than simply AssetImage or NetworkImage

**Comment by ReinBentdal** [comment]
Thanks for the feedback! Will look into it

**Comment by ReinBentdal** [comment]
A ImageProvider is now exposed in version 0.8.0
