### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by gedw99** [ReinBentdal/division#3]
It's possible to build flutter widgets from html.

**Comment by ReinBentdal** [comment]
Yes i know. But i think both packages are usefull in their own way. The goal of the html widgets is mainly to replecate html i think. This widgets goal is mainly to simplify the styling of flutter widgets and prevent unnecessary nesting. Please further explain what you mean.

A big rewrite of the package with many new features coming in a couple of days!

**Comment by gedw99** [comment]
what i meant was that its cool to be able to do the styling using css like semantics, but then you might as well go all the way and just drive everything using HTML.

**Comment by ReinBentdal** [comment]
Thanks for the response. Just released a major update.

**Comment by localpcguy** [comment]
FWIW, I disagree with the author of this issue. I like that this package keeps Flutter semantics but attempts to solve one of the issues I struggle with, that of deep nesting and having to wrap the same widget multiple times to get the styling I want.

**Comment by gedw99** [comment]
github.com/neohelden/Flutter-AdaptiveCards

**Comment by localpcguy** [comment]
I don't see how Adaptive Cards has anything to do with this repo or issue.

**Comment by gedw99** [comment]
Its orthogonal..
