### ISSUE TITLE
Dose Division support Flutter Web?

### ISSUE THREAD

**Issue by paulscliu** [ReinBentdal/division#33]
I tested the program from Reso Coder using Flutter Web
https://github.com/ResoCoder/flutter-division-tutorial

I imported Division 0.8.4+1 and it seems to be working.

**Comment by ReinBentdal** [comment]
I currently have no plans on supporting Flutter for web. So far this project has been a one person project and I simply do not have the time for it at the moment. 
But if it works, that's great!
Feel free to open an issue/ pull request if you find a bugs or things that could be improved

**Comment by paulscliu** [comment]
Thanks. I will close this issue
