### ISSUE TITLE
New widgets and naming scheme

### ISSUE THREAD

**Issue by moraispgsi** [ReinBentdal/division#34]
Hi, congratz on the library, its a great start. 

Are there any plans for future improvements? It seems that the next thing to do is to make more Styled widgets like Row -> StyledRow and Col -> StyledCol. Also if you find this to be a logic next step I would also advise you to use a new naming scheme for the widget classes Parent -> StyledContainer and Txt -> StyledText.

**Comment by ReinBentdal** [comment]
Thanks for the feedback! Yes i am considering scaling into more widgets, however my time to put into this project at the moment is quite limited. 
In the long run it might also be a good idea to rename the whole package to styled_widget, to make the name more suggestive. 
I disagree with the naming scheme you suggested. Having a completely different name for the styled widget would make it more difficult to remember. 
However something like this might be a good idea:
```dart
// format
[widget name] -> Styled[widget name]

Parent -> StyledParent
Txt -> StyledTxt
Img -> StyledImg
```
I have been trying to find a better name for `GestureClass` but currently haven`t found any.

For row/column im not sure if the best solution would be to make a single widget for them both or if there should be a widget for them each. Or even what to name them.

**Comment by moraispgsi** [comment]
Hi again, thanks for the response. I am sure the naming convention will become evident as the library progresses in development. For both Row and Col you could name the widget that joins them a LinearLayout or just LinearContainer. Or you could even place an optional children argument to the Parent class and increase the number of styles in ParentStyle.

**Comment by ReinBentdal** [comment]
Great suggestions. Actually, maybe the Parent widget could only take the parameter `children` instead of `child`. If there is only one child, which is also a Division widget, it could just be combined into one widget.
```dart
Parent(
  style: parentStyle,
  child: Txt(
    'some text',
    style: txtStyle,
  )
)
```
to
```dart
Txt(
  'some text',
  style: combinedStyle,
)
```
Hovewer i dont know how that would work performance-vise.
```dart
Parent(
  children: List<Widget>,
  style: ParentStyle,
  gesture: GestureClass,
)
```

**Comment by ReinBentdal** [comment]
It might actually not be a dumb idea to just omit the child property and change it with children in the `Parent` widget. When i look at some of the projects where i have used this package, the child of the `Parent` widget is in almost all cases a Row or Column (or another "children" widget).

**Comment by moraispgsi** [comment]
Yes, I think changing it to children gives the best user experience.

**Comment by ReinBentdal** [comment]
For now i have made the desicion to not make a "children" widget. The point of this package is to make the styling part of building widgets easier. They dont have to do everything. The structural part of building a widget tree is decoupled from the styling part. Structural elements as `Row`, `Column`, `ListView` etc takes care of the structural parts.
Right now i wont expand this package into these kinds of widgets. Will have to reconsider later

**Comment by moraispgsi** [comment]
It makes sense, I appreciate the logic behind the decision. Let's close this one for now.
