### ISSUE TITLE
onHighlightChanged

### ISSUE THREAD

**Issue by thize** [ReinBentdal/division#38]
Plz put onHighlightChanged, is better to do animations

**Comment by ReinBentdal** [comment]
Can you specify what you mean? How would it behave?

**Comment by thize** [comment]
In Gestures, it would behave like InkWell onHighlightChanged tag.

https://api.flutter.dev/flutter/material/MaterialButton/onHighlightChanged.html

**Comment by thize** [comment]
https://prnt.sc/q15q8j

**Comment by thize** [comment]
In fact, you already implemented this, but used the name isTap.
