### ISSUE TITLE
Upgrading from 0.8.6 to 0.8.7 broke the UI - child does not render

### ISSUE THREAD

**Issue by oysterpack** [ReinBentdal/division#43]
When I use 0.8.6 version, everything looks beautiful. However, starting with 0.8.7 version, anything wrapped within a Parent does not render the child widget. Looks like the bug is in **widget.dart**

```dart
if (child != null) ParentBuild(child: child);
```

should be

```dart
if (child != null) widgetTree = ParentBuild(child: child);
```

**Comment by ReinBentdal** [comment]
Wow, how did i miss that? Anyways thanks for the notise. An update has been released!
