### ISSUE TITLE
type 'double' is not a subtype of type 'bool'

### ISSUE THREAD

**Issue by bsergik** [ReinBentdal/division#46]
> ════════ Exception caught by widgets library ═══════════════════════════════════
> The following assertion was thrown building:
> type 'double' is not a subtype of type 'bool'
> 
> When the exception was thrown, this was the stack
> #0      CoreStyle.border package:division/src/style.dart:178
> ...
> ════════════════════════════════════════════════════════════════════════════════

Versions:
division: ^0.8.7+1
flutter: 1.12.13
dart: 2.7.0

Code to reproduce:
```dart
  final ParentStyle userCardStyle = ParentStyle()
    ..height(100)
    ..padding(horizontal: 20.0, vertical: 10)
    ..alignment.center()
    ..border(bottom: 1.0, color: Colors.white24);
```

**Comment by ReinBentdal** [comment]
This should now be fixed. Let me know if it works now (version 0.8.7+2)

**Comment by bsergik** [comment]
Now it works. Thank you!
