### ISSUE TITLE
The clone() function modifies the initial style !

### ISSUE THREAD

**Issue by yaitmou** [ReinBentdal/division#50]
### **Version**
The following issue was found on the version **0.8.7+2** of division package

###  **The issue**

Let's say I want to style a button and add tow state styles (active and inactive). I would create a parent button style the holds all the dimensions specs and then add tow additional styles for active and inactive states. I tried to achieve this with the clone function but it seems to override the parent style. That is all the buttons will sync and get the same style! 
Here is an example:

### **Example**
```dart
final rootButtonStyle = ParentStyle() 
  ..width(32)
  ..height(32)
  ..borderRadius(all: 16)
  ..border(all: 1)
  ..alignmentContent.center()

final activeButtonStyle = rootButtonStyle()
  ..clone()
  ..background.hex("#0D8E5D");

final disabledButtonStyle = rootButtonStyle()
  ..clone()
  ..background.hex("#919191");
```
In the above example, all the buttons will be ether in the active or disabled style, depending if I set `override` to  `ture` or not!

### **Hint**
I explored a bit the source code and found that the `clone()` function is simply calling the `add()` function **which is simply replacing the styles!**

**Comment by ReinBentdal** [comment]
You are still returning the original style. You should only have one dot for the clone method to instead return the cloned style:
```dart
final disabledButtonStyle = rootButtonStyle.clone()
  .. background.hex(#919191');
```

**Comment by yaitmou** [comment]
OOPS! Thanks for the light. I completely missed that double dot annotation :s
