### ISSUE TITLE
Autofocus Text Element whenn editable is set to true

### ISSUE THREAD

**Issue by muellercornelius** [ReinBentdal/division#51]
Hello,

I struggeling a bit with trying to autofocus an element as soon as i toggle the enable variable.

This is my code: 
```
txt(
   widget.category.name,
   style: TxtStyle()
      ..fontSize(26)
      ..fontWeight(FontWeight.w500)
      ..padding(left: 16)
      ..editable(
          enable: _editCategoryName,
          maxLines: 1,
          onChange: (name) {
                widget.category.name = name;
                widget.category.save();
           },
   },
),
```
In the second example (https://github.com/ReinBentdal/division/blob/master/example/example/example_form.dart) is one property called `autoFocus: true,` but when i use this property. I get an error: 

```
Compiler message:
lib/pages/todoListe.dart:66:25: Error: No named parameter with the name 'autoFocus'.
                        autoFocus: true,
```
I also tried using the focus node but i think I did it wrong.

It would be great if someone could show me how to accomplish that.

**Comment by ReinBentdal** [comment]
Hello. The reason is simple. The `autoFocus` feature is new and a release containing this feature is yet to release. The next release will contain this feature, and it will hopefully be out soon!

**Comment by muellercornelius** [comment]
Great ;) thank you ;)
