### ISSUE TITLE
Height on TxtStyle

### ISSUE THREAD

**Issue by cocacrave** [ReinBentdal/division#53]
TxtStyle..height doesn't work as expected.
TextStyle(height) works like line-height in css but TxtStyle..height is the container height I believe...
Is there a way to set line-height?

**Comment by ReinBentdal** [comment]
There is no current way of setting line-height. Can you give an example where a line-height would be benefitial over for example just setting the height or a top padding?

**Comment by cocacrave** [comment]
For long body of text with many lines, sometimes it looks nice to set some line-height so it doesn't look crowded. I believe height and padding doesn't solve for adding some height in line but rather overall body of text?

And I guess I was just confused because I expected height on TxtStyle to behave like height on TextStyle. Not sure if you have plans to implement that but I think it'd be nice :)

**Comment by ReinBentdal** [comment]
Thanks for the explanation. I will implement it for the next version!

**Comment by cocacrave** [comment]
That's awesome! Thanks

**Comment by uzuki-P** [comment]
I'm sorry for bumping up old issues, but is this already implemented?
I didn't see any option to set text line-height and the current height method still for text container height, not line-height
