### ISSUE TITLE
Support null safety 

### ISSUE THREAD

**Issue by nehal076** [ReinBentdal/division#66]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:division`
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See this [blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by ReinBentdal** [comment]
Thanks for the heads-up. I am currently busy with my studies and other projects. I cannot promise that i will implement null safety on my own. I would therefore greatly appreciate any help with the development. 

Great to see someone enjoying the package!

**Comment by psycura** [comment]
Guys, i did the required changes for personal use, so until the author will accept existing PR, you can use version from my repo:
[https://github.com/psycura/flutter_division_null_safety.git](https://github.com/psycura/flutter_division_null_safety.git
)
Important note: Use it for you risk

**Comment by wissemo** [comment]
@ReinBentdal Thanks for this great package,

what about null safety is it coming soon ?

**Comment by oleg79** [comment]
@wissemo there is a pull request https://github.com/ReinBentdal/division/pull/67
but I haven't got any remarks so far... :)

**Comment by mentor33** [comment]
> Thanks for the heads-up. I am currently busy with my studies and other projects. I cannot promise that i will implement null safety on my own. I would therefore greatly appreciate any help with the development.
> 
> Great to see someone enjoying the package!

we steal waiting

**Comment by nehal076** [comment]
@ReinBentdal Please accept the pull request and update this package to null-safety. It's been a long time now.

**Comment by GitGud31** [comment]
> @ReinBentdal Please accept the pull request and update this package to null-safety. It's been a long time now.

I'm actually refactoring my project today, I have to let go of this package unfortunately so I can migrate to null safety :/

**Comment by ReinBentdal** [comment]
Sorry for taking so long. I will accept it straight away

**Comment by ReinBentdal** [comment]
Package updated with null safety

**Comment by mentor33** [comment]
> Sorry for taking so long. I will accept it straight away

Why did you take all this time? I did not find a solution in my hand except to use other packages as an alternative, I hope the same situation will not be repeated and welcome back to division again
