### ISSUE TITLE
overflow.hidden() late Initialization error

### ISSUE THREAD

**Issue by elmobark** [ReinBentdal/division#70]
when using overflow.hidden() console print 
`LateInitializationError: Field '_direction@1189196404' has not been initialized.`
flutter 2.2.3
and here my flutter doctor
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1323 darwin-x64, locale en-SA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.59.0)
[✓] Connected device (3 available)
    ! Error: Elmobark’s iPhone is not connected. Xcode will continue when Elmobark’s iPhone is connected. (code -13)
• No issues found!`

**Comment by elmobark** [comment]
i think this project is died

**Comment by Awaleed** [comment]
I working on it

**Comment by elmobark** [comment]
@Awaleed @ReinBentdal PR this

**Comment by ReinBentdal** [comment]
fixed in pr
